name: Deploy Dist
on: [push, workflow_dispatch]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: |
          echo "Clone repo"
          echo "${{tojson(github)}}"
          git clone https://github.com/${{github.repository}}.git

